export const themes = [
  { label: "Aydınlık", value: "light" },
  { label: "Karanlık", value: "dark" },
  { label: "Kap Kek", value: "cupcake" },
  { label: "Bumblebee", value: "bumblebee" },
  { label: "Yakut", value: "emerald" },
  { label: "Kurumsal", value: "corporate" },
  { label: "Retro Dalgası", value: "synthwave" },
  { label: "Retro", value: "retro" },
  { label: "Cyberpunk", value: "cyberpunk" },
  { label: "Sevgililer Günü", value: "valentine" },
  { label: "Halloween", value: "halloween" },
  { label: "Okyanus", value: "aqua" },
  { label: "Siyah", value: "black" },
  { label: "Orman", value: "forest" },
  { label: "Drakula", value: "dracula" },
  { label: "Gece", value: "night" },
  { label: "Lüks", value: "luxury" },
  { label: "Kahve", value: "coffee" },
];
